### ISSUE TITLE
Server doesn't respond to more than one request

### ISSUE THREAD

**Issue by cofonseca** [cofonseca/WebListener#1]
When loading a page and letting it finish, you're able to navigate to other pages without issue.

If you stop loading a page before it's completely finished loading, then try to reload the page or navigate to another page, nothing happens, and the server will occasionally crash, breaking back to the shell.

In addition, attempting to reload the same page, even after a successful page load, doesn't seem to work.

**Comment by ghost** [comment]
Tried it on my machine. Multiple requests are processed without any issues.

**Comment by cofonseca** [comment]
@DropNib I went back and tried this again because I couldn't remember exactly what my issue was. The issue seems to be if you stop while a page is loading, then try to reload it. Or if you finish loading a page, then try to reload it. For some reason, the reload never seems to work.  

If I let a page load completely like normal, then try to navigate to another page, that works fine. 

I'll update the issue name and description.

**Comment by cofonseca** [comment]
Fixed.
