### ISSUE TITLE
CTRL + C should kill the listener.

### ISSUE THREAD

**Issue by cofonseca** [cofonseca/WebListener#4]
Pressing CTRL+C in the console should stop the listener, and return to a PowerShell prompt.

**Comment by ghost** [comment]
Created a fix. See #5 
It should however be noted that a C# application would be a better way to create a web server, because PowerShell has too many limits when it comes to parallelization and asynchronous execution.

**Comment by cofonseca** [comment]
@DropNib sorry for the delay - I forgot to take a look at your pull request right away and forgot about it! Your solution looks perfect and works great so I'll go ahead and merge it in.

I do agree that C# would be the ideal solution. This is primarily for personal use and just something that I wanted to try out.  

Appreciate the contributions!
